name: Trigger

on:
  pull_request:
    types: [opened, edited, synchronize]

permissions:
  actions: write
  contents: read

jobs:
  check-title-and-trigger:
    runs-on: ubuntu-latest
    if: startsWith(github.event.pull_request.title, 'deploy-github-pages')
    steps:
      - name: Sep Trigger 2 Workflow
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            await github.rest.actions.createWorkflowDispatch({
              owner: context.repo.owner,
              repo: context.repo.repo,
              workflow_id: 'fetch-files.yml',
              ref: context.payload.pull_request.head.ref
            });
