name: Deploy Trigger

on:
  pull_request:
    types: [opened, edited, synchronize]

jobs:
  check-and-trigger:
    runs-on: ubuntu-latest
    if: github.event.pull_request.title == 'deploy-github-pages'
    steps:
      - name: Trigger Fetch Files Workflow
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            await github.rest.actions.createWorkflowDispatch({
              owner: context.repo.owner,
              repo: context.repo.repo,
              workflow_id: 'fetch-files.yml',
              ref: context.payload.pull_request.head.ref
            });
